version: '3'

services:
  web:
    build:
      context: ./web
    ports:
      - 8080:80
    environment:
      AWS_ACCESS_KEY_ID: mock
      AWS_SECRET_ACCESS_KEY: mock
      APP_ENV: local
      QUEUE_URL: http://localstack:4566/000000000000/messages-queue.fifo
      DB_USER_NAME: app
      DB_USER_PASS: password
      DB_HOST: db
      DB_DATABASE: bbs
      TZ: "Asia/Tokyo"
    depends_on:
      - db
      - localstack

  worker:
    build:
      context: ./worker
    environment:
      AWS_ACCESS_KEY_ID: mock
      AWS_SECRET_ACCESS_KEY: mock
      APP_ENV: local
      QUEUE_URL: http://localstack:4566/000000000000/messages-queue.fifo
      DB_USER_NAME: app
      DB_USER_PASS: password
      DB_HOST: db
      DB_DATABASE: bbs
      TZ: "Asia/Tokyo"
    depends_on:
      - db
      - localstack

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bbs
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"

  localstack:
    image: localstack/localstack:latest
    environment: 
      - SERVICES=sqs
      - DEFAULT_REGION=ap-northeast-1
    ports:
      - 4566:4566
  
  migrate:
    build:
      context: ./migrate
    environment:
      DB_HOST: db
      DB_DATABASE: bbs
      DB_USER_NAME: app
      DB_USER_PASS: password
      TZ: "Asia/Tokyo"
    depends_on:
      - db

  terraform:
    build:
      context: ./terraform/local
    depends_on:
      - localstack